[package]
name = "simplex"
version = "0.1.0"
authors = ["tgrabham <trevor_grabham@sfu.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
